name:                 RayTracing
version:              0.1.0.0
visibility:           public
id:                   RayTracing-0.1.0.0-inplace
key:                  RayTracing-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           luisojeda@uchicago.edu
author:               Luis Ojeda
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/dist-newstyle/build/aarch64-osx/ghc-9.6.7/RayTracing-0.1.0.0/build

library-dirs:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/dist-newstyle/build/aarch64-osx/ghc-9.6.7/RayTracing-0.1.0.0/build

library-dirs-static:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/dist-newstyle/build/aarch64-osx/ghc-9.6.7/RayTracing-0.1.0.0/build

dynamic-library-dirs:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/dist-newstyle/build/aarch64-osx/ghc-9.6.7/RayTracing-0.1.0.0/build

data-dir:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/.

hs-libraries:         HSRayTracing-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/dist-newstyle/build/aarch64-osx/ghc-9.6.7/RayTracing-0.1.0.0/doc/html/RayTracing/RayTracing.haddock

haddock-html:
    /Users/luisojeda/functional-programming/final-project-luisojedacs/dist-newstyle/build/aarch64-osx/ghc-9.6.7/RayTracing-0.1.0.0/doc/html/RayTracing
